### ISSUE TITLE
ImportError: No module named 'settings'

### ISSUE THREAD

**Issue by nelsp** [kendlera/pg-server#1]
is there a file missing in the project?

**Comment by kendlera** [comment]
yup! Intentionally missing from the repo since it contains the settings for the server. You'll need to have a file pg-server/settings.py with `import os` and a `class Settings`. Within the settings class you'll need the global variables `HOST` `PORT` `DEBUG` `BASE_PATH` and `KEY` defined. I'll put up an example settings file tomorrow. I realized I'm also missing some endpoint descriptions from the README, so I'll update that as well.

**Comment by nelsp** [comment]
you don't have to do it now.  it can wait til you guys are up in vt.  ill
have a lot more questions (and need hand holding) later.
